yabe_main_homepage:
    pattern:  /
    defaults: { _controller: YabeMainBundle:Home:index }

YabeMainBundle_geoloc:
    resource: "@YabeMainBundle/Resources/config/routing/geoloc.yml"
    prefix:   /geoloc

YabeMainBundle_socialnetwork:
    resource: "@YabeMainBundle/Resources/config/routing/socialnetwork.yml"
    prefix:   /socialnetwork

YabeMainBundle_productinteractions:
    resource: "@YabeMainBundle/Resources/config/routing/productinteractions.yml"
    prefix:   /productinteractions

YabeMainBundle_product:
    resource: "@YabeMainBundle/Resources/config/routing/product.yml"
    prefix:   /product

YabeMainBundle_category:
    resource: "@YabeMainBundle/Resources/config/routing/category.yml"
    prefix:   /category
