<?php

namespace Yabe\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EvaluationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluationsRepository extends EntityRepository
{
}
