<?php

namespace Yabe\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductInteractionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductInteractionsRepository extends EntityRepository
{
}
