parameters:
#    yabe_user.example.class: Yabe\UserBundle\Example

services:
    coral_user.registration.form.type:
        class: Yabe\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: yabe_user_registration }

    yabe_user.profile.form.type:
        class: Yabe\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: yabe_user_profile }
