parameters:
#    yabe_user.example.class: Yabe\UserBundle\Example

services:
#    yabe_user.example:
#        class: %yabe_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
